### PR TITLE
Atomic type polyfill

### PR DESCRIPTION
**Pull request by MabezDev**
Add support for riscv critical sections too.

### CODE REVIEW

**Comment by bjoernQ** [comment]
I was about to submit a similar PR but would love to also have `riscv32imfc` and `riscv32i` covered
But also, haven't tested this yet

**Comment by MabezDev** [comment]
> I was about to submit a similar PR but would love to also have riscv32imfc and riscv32i covered

Latest commit _should_ cover the other targets :)

**Comment by MabezDev** [comment]
Tested and working on a esp32c3, ready for review!

**Comment by bjoernQ** [comment]
also tested it on BL602 - works fine 👍

**Review by Dirbaio — APPROVED** [review]
This is awesome, thank you! :)

**Comment by Dirbaio** [comment]
I'm going to refactor a bit to get rid of the "Deref" hack (I've never liked it, but now that we can polyfill the entire types from scratch it makes even less sense), then I'll release 0.1.4.

**Pull request merged**
